### ISSUE TITLE
Cannot read property 'grid' of undefined

### ISSUE THREAD

**Issue by edcoffin** [formio/ngFormioGrid#28]
Hey guys,

Running Chrome 55.0.2883.95

Using `bower install ng-formio-grid`:

we get:

```
Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#>=1.4.0 which resolved to 1.5.11 and is required by angular-bootstrap#2.4.0, angular-bootstrap#1.3.3
    2) angular#>=1.4.0 1.5.x which resolved to 1.5.11 and is required by angular-ui-grid#4.0.2
    3) angular#>=1.2.18 which resolved to 1.5.11 and is required by angular-ui-select#0.19.6
    4) angular#^1.6.1 which resolved to 1.6.1 and is required by ng-formio#2.8.2, ng-formio-grid#0.12.1
    5) angular#>=1.2.0 <1.7.0 which resolved to 1.6.1 and is required by angular-moment#1.0.1
    6) angular#>= 1.3.6 which resolved to 1.6.1 and is required by angular-ui-mask#1.8.8-beta.1
    7) angular#>1.2.0 which resolved to 1.6.1 and is required by ng-file-upload#12.2.13
    8) angular#1.6.1 which resolved to 1.6.1 and is required by angular-sanitize#1.6.1
```

I chose 4.... then

    1) angular-bootstrap#^1.2.0 which resolved to 1.3.3 and is required by bootstrap-ui-datetime-picker#2.5.4
    2) angular-bootstrap#^2.4.0 which resolved to 2.4.0 and is required by ng-formio#2.8.2pyh

I chose option2.

I use wiredep -s index.html to load all the dependencies:

```
<html>
    <head>
      <!-- bower:css -->
      <link rel="stylesheet" href="bower_components/angular-ui-grid/ui-grid.css" />
      <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
      <link rel="stylesheet" href="bower_components/angular-ui-select/dist/select.css" />
      <link rel="stylesheet" href="bower_components/ng-formio/css/formio.css" />
      <!-- endbower -->
    </head>
    <body ng-app="formioForm">
      <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
      <![endif]-->

      <formio src="'https://myapp.form.io/ecoffintest'"></formio>
 
      <formio-grid src="'https://myapp.form.io/ecoffintest'"></formio-grid>

      <!-- bower:js -->
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/angular-ui-grid/ui-grid.js"></script>
      <script src="bower_components/ng-file-upload/ng-file-upload.js"></script>
      <script src="bower_components/moment/moment.js"></script>
      <script src="bower_components/angular-moment/angular-moment.js"></script>
      <script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
      <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
      <script src="bower_components/bootstrap-ui-datetime-picker/dist/datetime-picker.js"></script>
      <script src="bower_components/signature_pad/signature_pad.js"></script>
      <script src="bower_components/angular-ui-mask/dist/mask.js"></script>
      <script src="bower_components/blob-polyfill/Blob.js"></script>
      <script src="bower_components/file-saver.js/FileSaver.js"></script>
      <script src="bower_components/angular-file-saver/dist/angular-file-saver.bundle.js"></script>
      <script src="bower_components/angular-ui-select/dist/select.js"></script>
      <script src="bower_components/ng-formio/dist/formio.js"></script>
      <script src="bower_components/ng-formio-grid/dist/ng-formio-grid.js"></script>
      <!-- endbower -->

      <script type="text/javascript">
        angular.module('formioForm', ['ngFormioGrid']);
      </script>

    </body>
  </html>
```
The form view / submit works fine.

However with data grid never loads with the following errors:

```
angular.js:14328 TypeError: element.html(...).show is not a function
    at Object.link (http://localhost:8000/bower_components/ng-formio-grid/dist/ng-formio-grid.js:51:30)
    at http://localhost:8000/bower_components/angular/angular.js:1291:18
    at http://localhost:8000/bower_components/angular/angular.js:10246:44
    at invokeLinkFn (http://localhost:8000/bower_components/angular/angular.js:10252:9)
    at nodeLinkFn (http://localhost:8000/bower_components/angular/angular.js:9641:11)
    at compositeLinkFn (http://localhost:8000/bower_components/angular/angular.js:8881:13)
    at compositeLinkFn (http://localhost:8000/bower_components/angular/angular.js:8884:13)
    at publicLinkFn (http://localhost:8000/bower_components/angular/angular.js:8746:30)
    at http://localhost:8000/bower_components/angular/angular.js:1843:27
    at Scope.$eval (http://localhost:8000/bower_components/angular/angular.js:17972:28) <div src="'https://eeypyxcviiwgrat.form.io/ecoffintest'" class="ng-isolate-scope">
(anonymous) @ angular.js:14328
(anonymous) @ angular.js:10837
invokeLinkFn @ angular.js:10254
nodeLinkFn @ angular.js:9641
compositeLinkFn @ angular.js:8881
compositeLinkFn @ angular.js:8884
publicLinkFn @ angular.js:8746
(anonymous) @ angular.js:1843
$eval @ angular.js:17972
$apply @ angular.js:18072
bootstrapApply @ angular.js:1841
invoke @ angular.js:4842
doBootstrap @ angular.js:1839
bootstrap @ angular.js:1859
angularInit @ angular.js:1744
(anonymous) @ angular.js:32977
trigger @ angular.js:3314
2017-01-26 10:06:48.599 angular.js:14328 Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite! See: http://docs.angularjs.org/api/angular.element
http://errors.angularjs.org/1.6.1/jqLite/nosel
    at http://localhost:8000/bower_components/angular/angular.js:68:12
    at Object.JQLite [as element] (http://localhost:8000/bower_components/angular/angular.js:3067:13)
    at setLoading (http://localhost:8000/bower_components/ng-formio-grid/dist/ng-formio-grid.js:117:39)
    at http://localhost:8000/bower_components/ng-formio-grid/dist/ng-formio-grid.js:363:15
    at processQueue (http://localhost:8000/bower_components/angular/angular.js:16648:37)
    at http://localhost:8000/bower_components/angular/angular.js:16692:27
    at Scope.$eval (http://localhost:8000/bower_components/angular/angular.js:17972:28)
    at Scope.$digest (http://localhost:8000/bower_components/angular/angular.js:17786:31)
    at http://localhost:8000/bower_components/angular/angular.js:18011:26
    at completeOutstandingRequest (http://localhost:8000/bower_components/angular/angular.js:6111:10) Possibly unhandled rejection: {}
(anonymous) @ angular.js:14328
(anonymous) @ angular.js:10837
processChecks @ angular.js:16674
$eval @ angular.js:17972
$digest @ angular.js:17786
(anonymous) @ angular.js:18011
completeOutstandingRequest @ angular.js:6111
(anonymous) @ angular.js:6390
2017-01-26 10:06:48.609 angular.js:14328 TypeError: Cannot read property 'grid' of undefined
    at ng-formio-grid.js:373
    at angular.js:19916
    at completeOutstandingRequest (angular.js:6111)
    at angular.js:6390
(anonymous) @ angular.js:14328
(anonymous) @ angular.js:10837
(anonymous) @ angular.js:19919
completeOutstandingRequest @ angular.js:6111
(anonymous) @ angular.js:6390
2017-01-26 10:06:48.610 angular.js:14328 TypeError: Cannot read property 'grid' of undefined
    at http://localhost:8000/bower_components/ng-formio-grid/dist/ng-formio-grid.js:373:124
    at http://localhost:8000/bower_components/angular/angular.js:19916:31
    at completeOutstandingRequest (http://localhost:8000/bower_components/angular/angular.js:6111:10)
    at http://localhost:8000/bower_components/angular/angular.js:6390:7 Possibly unhandled rejection: {}
(anonymous) @ angular.js:14328
(anonymous) @ angular.js:10837
processChecks @ angular.js:16674
$eval @ angular.js:17972
$digest @ angular.js:17786
$apply @ angular.js:18080
(anonymous) @ angular.js:19924
completeOutstandingRequest @ angular.js:6111
(anonymous) @ angular.js:6390
```

**Comment by zackurben** [comment]
@edcoffin try manually placing the jquery dependency before angular; this should fix the first issue, because Angulars built-in jqLite doesnt support `.show()` or `.hide()`.

**Comment by edcoffin** [comment]
That fixed it. Thanks @zackurben !
